### ISSUE TITLE
desisim master broken with desitarget master

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#245] opened 2017-06-28 21:28 UTC
desisim/master has gotten out of sync with desitarget/master, e.g. `desisim.templates.LRG.make_templates()` calling `desitarget.cuts.isLRG()` with a keyword `w2flux` that no longer exists.  Note: `desitarget.cuts.isLRG_colors()` has an unused `w2flux` parameter but `desitarget.cuts.isLRG()` does not.

Assigning to both @moustakas and @geordie666 to figure out whether the fix is in desisim, desitarget, or both.

Example test failure from desisim/master when using desitarget/master:
```
======================================================================
ERROR: test_input_redshift (desisim.test.test_templates.TestTemplates)
Test that we can input the redshift for a representative galaxy and star class.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/test/test_templates.py", line 114, in test_input_redshift
    flux, wave, meta = Tx.make_templates(self.nspec, redshift=redshift, seed=self.seed)
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/templates.py", line 981, in make_templates
    verbose=verbose)
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/templates.py", line 710, in make_galaxy_templates
    w2flux=synthnano[:, 7])
TypeError: isLRG() got an unexpected keyword argument 'w2flux'
```

**Comment by geordie666** [comment] 2017-06-28 22:01
This is my fault. I removed w2flux because it wasn't actually used in the code, forgetting that the sims might always pass w2flux regardless of whether it was used. I'll add it back in as a "dummy input" in the next hour, and @moustakas can merge as soon as he sees my PR.

**Comment by moustakas** [comment] 2017-06-28 22:01
Yes that's exactly right. Thanks for the fix!

**Comment by moustakas** [comment] 2017-06-29 02:09
Fixed in https://github.com/desihub/desitarget/pull/194.

**Closed by moustakas** 2017-06-29 02:09 UTC
Labels: bug

**Comment by sbailey** [comment] 2017-06-30 18:23
Reopening this since desisim/master and desitarget/master are still incompatible.  The fix is probably on the desitarget side but I'll just reopen this issue.  Example traceback below.  Please take a look @geordie666 and @moustakas .  Thanks.
```
======================================================================
ERROR: test_input_wave (desisim.test.test_templates.TestTemplates)
Confirm that we can specify the wavelength array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/test/test_templates.py", line 52, in test_input_wave
    flux, wave, meta = lrg.make_templates(self.nspec, seed=self.seed)
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/templates.py", line 981, in make_templates
    verbose=verbose)
  File "/global/common/edison/contrib/desi/code/desisim/master/build/lib/desisim/templates.py", line 710, in make_galaxy_templates
    w2flux=synthnano[:, 7])
  File "/global/common/edison/contrib/desi/code/desitarget/master/py/desitarget/cuts.py", line 106, in isLRG
    lrg &= (rflux_snr > 0) # and rallmask == 0
TypeError: unorderable types: NoneType() > int()
```

**Comment by geordie666** [comment] 2017-06-30 18:49
I think the issue is possibly now on the `desisim` side. The new LRG cuts in `desitarget` require

```
rflux_snr=None, zflux_snr=None, w1flux_snr=None,
gflux_ivar=None
```

as well as the fluxes, to run the `isLRG()` function. But, `desisim` is only passing the fluxes:

```
   colormask = self.colorcuts_function(
                        gflux=synthnano[:, 1],
                        rflux=synthnano[:, 2],
                        zflux=synthnano[:, 4],
                        w1flux=synthnano[:, 6],
                        w2flux=synthnano[:, 7])
```
(in this context, `colorcuts_function()` is an alias for `isLRG()`)

So, `desisim` either needs to generate a noise model (shudder) or needs to pass ivars and snrs to `isLRG()`.

Perhaps the best solution would be for `desisim` to pass things to `isLRGcolors()` instead of to`isLRG`? I think that's the quick fix?
