### ISSUE TITLE
add option to run quickquasars without adding a continuum

### ISSUE THREAD

**Issue by jvstermer** [desihub/desisim#499] opened 2019-07-05 16:47 UTC
Add option to run quickquasars without adding a continuum. This will give the same resolution as dressed mocks to the raw mocks. @londumas What do you think?

**Comment by alxogm** [comment] 2020-03-09 22:18
@jvstermer Did you did something along this lines? And still think is useful? With Andreu we are discussing whether to add an option to save the continum, or to save the flux divided by the continum... So we would like to know if you have a branch or something that already do this?

**Comment by jvstermer** [comment] 2020-03-18 16:00
@alxogm I do have a local branch that I can push, where I don't apply the continuum template. 
I looked at the impact on the results and it didn't seem like the problem we have with the distortion matrix came from there. 
But Jim does think that having access to the continuum, i.e. saving it in the fits file for example would be a good idea.

**Comment by andreufont** [comment] 2020-03-18 16:07
I think we have two options that would work:
 - Add an option in quickquasars (--divide-continuum) that divide by the continuum at the end stage, before printing to file. It would have to divide the noise estimate as well, or rather multiply the noise variance by continuum squared. This would allow avoid having to also write the continuum to file.
 - We could run quickquasars with QSO templates, that are easier to reproduce in post-process, i.e., use the meta data already printed in the truth file to reproduce the continuum as a funtion in wavelength later on. Not sure how difficult it is to actually reproduce the continuum though.

**Comment by alxogm** [comment] 2020-03-18 16:37
Thanks @jvstermer, it is good to know that saving the continuum is useful for . 

With Andreu we discussed a few options, I'm checking on how difficult is to recover the continuum when using QSO, since for SIMQSO I have not succeeded yet...

@jvstermer feel free to explore the options too.. 

Thanks!

**Comment by alxogm** [comment] 2021-02-10 16:02
Closing this since we have an option now that saves the true continuum.

**Closed by alxogm** 2021-02-10 16:02 UTC
