### ISSUE TITLE
Apply dust extinction on simulated spectra

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#445] opened 2018-10-31 16:07 UTC
Need to apply dust extinction on simulated spectra.
We currently have an inconsistency in the sims. The ETC adds extra exposure time based on the E(B-V),
but the extinction is not applied to the spectra!

**Comment by moustakas** [comment] 2018-10-31 16:21
This is a duplicate of https://github.com/desihub/desitarget/issues/284 and is awaiting https://github.com/desihub/desispec/issues/513.

**Comment by julienguy** [comment] 2018-10-31 16:26
Thanks John. I suggest we let this ticket open until it is resolved in desitarget.

**Comment by moustakas** [comment] 2018-12-02 15:46
Done in https://github.com/desihub/desitarget/pull/425.

**Closed by moustakas** 2018-12-02 15:46 UTC
Labels: bug
