### ISSUE TITLE
Update quickbrick and quickgen to specsim v0.5

### ISSUE THREAD

**Issue by dkirkby** [desihub/desisim#161] opened 2016-09-18 20:07 UTC
The specsim exposure time parameter moved from `qsim.instrument` to the new`qsim.observation` in v0.5, but quickbrick and quickgen are still setting the value in `qsim.instrument` (which does not raise any exception, since python allows you to add attributes to an object on the fly).  The end result is that the exposure time is always fixed at 1000s.

This issue is to fix this problem, test the fix, and check for any other gotchas with the transition to specsim v0.5.

Thanks to @moustakas for flagging this!

**Comment by sbailey** [comment] 2016-09-19 17:26
Thanks for starting an issue about this.  We really should have unit tests that catch this sort of change-in-API problems.  This one is a bit tricky because of how the exposure time is set via a directly exposed member variable instead of a function (which generally I like instead of the super-strict C++ style "hide every variable and provide getter/setter functions", but there sometimes are gotchas).  Some basic sanity check unit tests would have at least caught the symptom to prompt us to go find the problem:
* do longer exposure times generate lower S/N spectra?
* do higher airmass observations generate noisier spectra?
* are bright time spectra noisier than dark time spectra?
* etc.

**Comment by dkirkby** [comment] 2016-09-19 19:00
specsim already has some functional unit tests along those lines, but they don't help when another program isn't using specsim correctly (due to an API change in this case).

The unit test problems in desisim are more basic since the quickbrick program on the master branch does not even run currently, as far as I can tell.  I will open a separate issue about that.

**Comment by sbailey** [comment] 2016-09-19 23:15
Yes, I specifically was referring to unittests in specsim that should catch if we are not using an external library correctly.

**Comment by dkirkby** [comment] 2016-09-19 23:35
I can't think of any unit test in specsim that could have caught this problem.   Did you have something in mind?

**Comment by sbailey** [comment] 2016-09-19 23:47
e.g. the list in my initial reply, in particular "do longer exposure times generate lower S/N spectra".  Although that wouldn't have actually crashed due to this API change, it would have caught that setting `qsim.instrument.exptime` didn't actually seem to have any effect anymore.

**Comment by moustakas** [comment] 2016-09-20 00:29
I think the units tests @sbailey has proposed belong in the (non-existent) units tests for ```quickbrick```.  Indeed, I "discovered" this issue precisely because I was finding (by running ```quickbrick```) that longer exposure times were not yielding higher-S/N spectra.

**Comment by dkirkby** [comment] 2016-09-20 00:39
@sbailey The tests you described would have to be in desisim, not specsim, to catch errors like this.  The corresponding unit tests in specsim don't help because they were updated at the same time as the API.

**Comment by sbailey** [comment] 2016-09-20 21:58
Misreading comments.  Yes, the tests I'm suggesting have to be in desisim to catch the fact that desisim was using the wrong API to specsim.  No specsim unit test could catch that an external package was using it incorrectly.

I'm working on quickbrick unit tests and updates now and running into my favorite topic of astropy.io.fits bugs.

**Comment by sbailey** [comment] 2016-10-08 00:08
Related: @dkirkby how do we set the airmass now?  From existing quickgen code it looks like it used to be set via `specsim.simulator.Simulator.airmass` but that doesn't work now (or perhaps that was never the right method).  I found an `airmass` attribute in the `Moon` object, but changing `qsim.atmosphere.moon.airmass` seems to have no effect — I always get the same sky spectrum back.  This was found via a new airmass test in PR #169 which is properly failing — quickgen is trying to alter the airmass but that isn't impacting the sky spectrum as it should.

**Comment by sbailey** [comment] 2016-10-08 00:13
Correction: quickgen is setting `Simulator.atmosphere.airmass` which does exist as a parameter but doesn't seem to have any effect.  specsim bug or user misunderstanding of API?

**Comment by dkirkby** [comment] 2016-10-09 15:47
There are now two ways to set the airmass in specsim:
 * explicitly via the `atmosphere.airmass` config parameter.
 * implicitly via the `source.location` and `observation.pointing` parameters.

The explicit / implicit mode is currently determined by whether the source (x, y) position (in length units) on the focal plane is specified or not, but a more obvious scheme would be an improvement.

I inadvertently changed the default to the implicit mode in v0.5 of `desi.yaml`, which I think explains your unit test result.  I just made a simple commit to master to undo this, and added comments in `desi.yaml` at the relevant places to better explain the new implicit / explicit logic.  Can you re-run with the updated specsim master and let me know?

**Comment by sbailey** [comment] 2016-10-10 18:42
@rstaten confirmed in #169 that atmosphere.airmass works again for desi with specsim master.  Thanks.

@dkirkby is there a simple fix that could be added to quickgen to switch back to explicit airmass mode even after reading in desi.yaml so that it would work with specsim/v0.5?  If we need to cut a new specsim tag, ok, but if we can do something simple to work with specsim/v0.5 and the future, that would be better.  Let's not put `source.location` and `observation.pointing` logic into quicken (yet?), but maybe simply unsetting the source position or flipping some switch post-facto would do it?

**Comment by sbailey** [comment] 2016-10-11 18:17
I'm still confused about how to set the airmass.  Using specsim master (__version__ 0.5dev523.dev530 __githash__ 391f269e782e8b270659208379026293361544f4) I tried to change the airmass via the following code, but still got the same sky spectrum:
```python
import specsim.simulator
from specsim.atmosphere import Moon
import astropy.units as u

qsim = specsim.simulator.Simulator('desi')
qsim.observation.exposure_time = 1000 * u.s

wave = np.arange(3500, 9900) * u.Angstrom
flux = np.zeros(len(wave)) * u.erg / (u.s * u.cm**2 * u.Angstrom)

qsim.atmosphere.airmass = 1.0
qsim.source.update_in('sky', 'sky', wave, flux)
qsim.source.update_out()
qsim.simulate()
wx = qsim.camera_output[2]['wavelength']
sky1 = qsim.camera_output[2]['num_sky_electrons']

qsim.atmosphere.airmass = 2.0
qsim.source.update_in('sky', 'sky', wave, flux)
qsim.source.update_out()
qsim.simulate()
sky2 = qsim.camera_output[2]['num_sky_electrons']

np.all(sky1-sky2 == 0)
```
But the quickgen tests changing airmass do pass.  What's wrong with the above code?

**Comment by dkirkby** [comment] 2016-10-11 18:39
The only component of the sky spectrum that currently depends on airmass is scattered moon, so my guess is that the moon is below the horizon here (or else you are not using the master version of `desi.yaml`).

**Comment by sbailey** [comment] 2016-10-11 18:40
I spun this into desihub/specsim#49 -- I find that if I create two different simulators at different airmasses, it works as expected, but if I try to change the airmass of a pre-existing Simulator, it doesn't work.

The sky spectrum should scale with airmass, even when the moon is down.

**Comment by dkirkby** [comment] 2016-10-11 18:42
Yes, you're right (assuming the `extinct_emission` flag is set, which it is by default now).

**Comment by sbailey** [comment] 2016-10-11 20:22
IIUC, that parameter controls the scaling of the *extinction* of the sky lines, but there is also an airmass dependence of the airglow itself.  i.e. higher airmass = more airglow.  e.g. see http://adsabs.harvard.edu/abs/1998NewAR..42..503B

**Comment by dkirkby** [comment] 2016-10-11 21:28
The airmass dependence of airglow has never been included in the simulation but is on the list.

**Comment by dkirkby** [comment] 2016-10-11 23:06
To close the loop here, the problem with your test above is that you need to copy the results of the first simulation, so they are not overwritten by the second simulation.  Details at desihub/specsim#49.

**Comment by sbailey** [comment] 2016-10-12 00:09
Thanks; I hadn't realized that the Simulator internal arrays were re-used.

Including airmass dependence of airglow should be a high priority prior to the full survey data challenge.  I added that comment to pre-existing desihub/specsim#2 .

I've added a small update to quickgen in PR #169 to explicitly set `qsim.source.focal_xy` if needed so that the varying airmass tests work with both specsim master (which sets it already) and specsim v0.5 (which doesn't).  That along with PR #161 (fixes to quickbrick) will close this issue.

**Comment by dkirkby** [comment] 2016-10-12 00:22
I was going to suggest that you set `focal_x,y` but I wasn't sure if that would work because those parameters are not instantiated in the config when they are commented out.  Its the right thing to try though, so lets see if the test passes...

**Comment by sbailey** [comment] 2016-10-12 00:27
I checked that setting `focal_xy` works with specsim v0.5 completely independently of quickgen, and then implemented that method in quickgen and confirmed that the tests pass with both specsim v0.5 and master (previously the airmass test only worked on master).  The parameter was there but set to `None` when using the specsim v0.5 `desi.yaml`.

Note that Travis does not run tests that require specsim because of memory limitations (see desihub/specsim#43), but I ran those tests on my laptop prior to pushing.

**Closed** 2016-10-12 00:39 UTC
